# MMLab | Phase 1 | Ensuring Data Sanity

From past experience I have noted that, sometimes the data is "pre-normalised" which causes problems later... This time making sure that this isn't the case

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

main_df = pd.read_csv("ALL_DATA/Raw_data/qm9summary_clean.csv")
# main_df = pd.read_csv("ALL_DATA/Raw_data/qm9dual_clean.csv")

main_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128294 entries, 0 to 128293
Data columns (total 36 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   field1         128294 non-null  int64
 1   unnamed:0      128294 non-null  int64
 2   mol_id         128294 non-null  int64
 3   smiles         128294 non-null  str
 4   a              128294 non-null  float64
 5   b              128294 non-null  float64
 6   c              128294 non-null  float64
 7   mu             128294 non-null  float64
 8   alpha          128294 non-null  float64
 9   homo           128294 non-null  float64
 10  lumo           128294 non-null  float64
 11  gap            128294 non-null  float64
 12  r2             128294 non-null  float64
 13  zpve           128294 non-null  float64
 14  u0             128294 non-null  float64
 15  u298           128294 non-null  float64
 16  h298           128294 non-null  float64
 17  g298           128294 non-null  float64
 18  cv             128294 non-null  float64
 19  u0_atom        128294 non-null  float64
 20  u298_atom      128294 non-null  float64
 21  h298_atom      128294 non-null  float64
 22  g298_atom      128294 non-null  float64
 23  molecule_name  128294 non-null  str
 24  count          128294 non-null  float64
 25  mean           128294 non-null  float64
 26  std            128294 non-null  float64
 27  min            128294 non-null  float64
 28  25%            128294 non-null  float64
 29  50%            128294 non-null  float64
 30  75%            128294 non-null  float64
 31  max            128294 non-null  float64
 32  gini_p         128294 non-null  float64
 33  gini_n         128294 non-null  float64
 34  f_n_avg        128294 non-null  float64
 35  f_p_avg        128294 non-null  float64
dtypes: float64(31), int64(3), str(2)
memory usage: 35.2 MB

In [2]:
main_df.describe()

,field1,unnamed:0,mol_id,a,b,c,mu,alpha,homo,lumo,...,std,min,25%,50%,75%,max,gini_p,gini_n,f_n_avg,f_p_avg
count,128294.000000,128294.000000,128294.000000,128294.000000,128294.000000,128294.000000,128294.000000,128294.000000,128294.000000,128294.000000,...,128294.000000,128294.000000,128294.000000,128294.000000,128294.000000,128294.000000,128294.000000,1.282940e+05,128294.000000,128294.000000
mean,64146.500000,64146.500000,64766.445726,10.093439,1.406242,1.128207,2.690722,75.414881,-0.239993,0.012377,...,0.116768,-0.334433,-0.018196,0.008046,0.035661,0.204643,0.530691,5.865782e-01,-0.090507,0.060792
std,37035.432055,37035.432055,37631.941896,1848.472880,1.616560,1.118275,1.520871,8.120211,0.021823,0.046199,...,0.035837,0.157270,0.018655,0.011756,0.023571,0.091906,0.141625,1.280691e-01,0.044540,0.027037
min,0.000000,0.000000,1.000000,0.000000,0.337120,0.331180,0.000000,6.310000,-0.428600,-0.175000,...,0.000899,-0.911565,-0.192606,-0.072585,-0.013644,-0.001013,0.000000,-2.020280e-16,-0.758101,0.000865
25%,32073.250000,32073.250000,32133.250000,2.554810,1.087292,0.908865,1.580100,70.700000,-0.252400,-0.022600,...,0.094869,-0.447980,-0.026964,-0.000069,0.015728,0.134293,0.426905,5.159319e-01,-0.111715,0.043799
50%,64146.500000,64146.500000,64242.500000,3.085430,1.367370,1.083810,2.486700,75.710000,-0.241100,0.013200,...,0.114552,-0.302308,-0.014547,0.004783,0.033830,0.189395,0.527557,6.058053e-01,-0.084861,0.055414
75%,96219.750000,96219.750000,97683.750000,3.838732,1.655393,1.285170,3.619500,80.680000,-0.229000,0.050400,...,0.138749,-0.214027,-0.005033,0.015157,0.052486,0.265501,0.636584,6.785481e-01,-0.060845,0.071733
max,128293.000000,128293.000000,129786.000000,619867.683140,437.903860,282.945450,29.556400,196.620000,-0.101700,0.193500,...,0.374214,-0.000946,0.104329,0.157964,0.239074,0.560853,0.904263,8.982772e-01,-0.000864,0.448761

In [3]:
main_df.columns.to_list()

['field1',
 'unnamed:0',
 'mol_id',
 'smiles',
 'a',
 'b',
 'c',
 'mu',
 'alpha',
 'homo',
 'lumo',
 'gap',
 'r2',
 'zpve',
 'u0',
 'u298',
 'h298',
 'g298',
 'cv',
 'u0_atom',
 'u298_atom',
 'h298_atom',
 'g298_atom',
 'molecule_name',
 'count',
 'mean',
 'std',
 'min',
 '25%',
 '50%',
 '75%',
 'max',
 'gini_p',
 'gini_n',
 'f_n_avg',
 'f_p_avg']

In [17]:
main_df.head()

,field1,unnamed:0,mol_id,smiles,a,b,c,mu,alpha,homo,...,std,min,25%,50%,75%,max,gini_p,gini_n,f_n_avg,f_p_avg
0,0,0,1,C,157.71180,157.709970,157.706990,0.0000,13.21,-0.3877,...,0.117221,-0.210448,0.051667,0.051667,0.051667,0.051667,0.000000,0.0,-0.210448,0.051667
1,1,1,2,N,293.60975,293.541110,191.393970,1.6256,9.46,-0.2570,...,0.286722,-0.429766,-0.006358,0.134779,0.141083,0.159995,0.039135,0.0,-0.429766,0.143184
2,2,2,3,O,799.58812,437.903860,282.945450,1.8511,6.31,-0.2928,...,0.273664,-0.316037,-0.079036,0.157964,0.157964,0.157964,0.000000,0.0,-0.316037,0.157964
3,3,3,4,C#C,0.00000,35.610036,35.610036,0.0000,16.28,-0.2845,...,0.052011,-0.047449,-0.047449,-0.002406,0.042637,0.042637,0.000000,0.0,-0.047449,0.042637
4,4,4,5,C#N,0.00000,44.593883,44.593883,2.8937,12.99,-0.3604,...,0.232923,-0.259298,-0.106338,0.046622,0.122268,0.197914,0.309346,0.0,-0.259298,0.122268

In [ ]:
# What?